requires 'perl'          => '5.28.0';
requires 'JSON'          => '4.03';
requires 'HTTP::Tiny'    => '0.076';
requires 'Path::Tiny'    => '0.118';
requires 'Text::CSV'     => '2.00';
requires 'Algorithm::KMeans';
requires 'YAML::XS'      => '0.89';
requires 'String::ShellQuote' => '1.04';
requires 'File::Slurp'       => '9999.24';
requires 'MIME::Base64'      => '3.15';
requires 'File::Type'        => '1.40';
requires 'Curses'            => '1.51';